PhotoAlbum.Client/Models/PhotoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoAlbum.Client.Models
{
    public class PhotoViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public byte[] Image { get; set; }
        public string ImageMimeType { get; set; }
    }
}

PhotoAlbum.Client/Models/PhotoViewModels.cs
using PhotoAlbum.Client.Filters;
using PhotoAlbum.Common.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhotoAlbum.Client.Models
{
    public class PhotoViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime CreationDate { get; set; }
        public string OwnerName { get; set; }
        public double Rating { get; set; }
    }

    public class CreatePhotoViewModel
    {
        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(500)]
        public string Description { get; set; }

        [ValidateFile]
        public HttpPostedFileBase Image { get; set; }
    }

    public class EditPhotoViewModel
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Title { get; set; }

        [Required]
        [StringLength(500)]
        public string Description { get; set; }
    }

    public class PhotoVoteViewModel
    {
        [Required]
        public int PhotoId { get; set; }

        [Required]
        [Range(0, 5)]
        public int Rating { get; set; }
    }

    public class SortPhotoViewModel
    {
        public string Sorting { get; set; }
        public string ByCreationDate { get; } = SortOrder.ByCreationDate.ToString();
        public string ByRating { get; } = SortOrder.ByRating.ToString();
    }

    public class UserPageViewModel
    {
        public SortPhotoViewModel SortPhoto { get; set; } = new SortPhotoViewModel();
        public string UserName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
    }
}

PhotoAlbum.Client/Controllers/PhotoController.cs
using AutoMapper;
using Newtonsoft.Json;
using PhotoAlbum.Client.BusinessServices.Interfaces;
using PhotoAlbum.Client.BusinessServices.Services;
using PhotoAlbum.Client.Dto;
using PhotoAlbum.Client.Filters;
//using PhotoAlbum.Client.Model.Services;
using PhotoAlbum.Client.Models;
using PhotoAlbum.Common.Enums;
using PhotoAlbum.Common.ErrorCodes;
using PhotoAlbum.Common.Exceptions;
using PhotoAlbum.Common.Helpers;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace PhotoAlbum.Client.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IPhotoAlbumService _photoAlbumService;
        private readonly IUserService _userService;

        public PhotoController(IPhotoAlbumService photoAlbumService, IUserService userService)
        {
            _photoAlbumService = photoAlbumService;
            _userService = userService;
        }
        
        public async Task<ActionResult> Index()
        {
            var model = new SortPhotoViewModel();

            return View(model);
        }

        public async Task<ActionResult> UserPage(string username)
        {
            var userFullNameDto = await _userService.GetUserFullNameAsync(username);
            var model = Mapper.Map<UserPageViewModel>(userFullNameDto);
            model.UserName = username;

            return View(model);
        }

        public async Task<ActionResult> UserPageManage(string username)
        {
            ViewBag.UserName = username;
            ViewBag.Manage = "manage";

            if (username != User.Identity.Name)
            {
                throw new UserIsNotAuthorizedException(ErrorCodes.UserIsNotAuthorized);
            }

            var model = new UserPageViewModel() { UserName = User.Identity.Name };

            return View(model);
        }

        [Authorize]
        public ActionResult CreatePhoto(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            var model = new CreatePhotoViewModel();

            return PartialView(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreatePhoto(CreatePhotoViewModel model, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            if (model.Image != null)
            {
                using (var binaryReader = new BinaryReader(model.Image.InputStream))
                {
                    Session["PhotoFileImageData"] = binaryReader.ReadBytes(model.Image.ContentLength);
                }
                Session["PhotoFileMimeType"] = model.Image.ContentType;
                Session["PhotoFileName"] = Path.GetFileName(model.Image.FileName);
            }

            if (model.Image == null && Session["PhotoFileImageData"] != null)
            {
                if (ModelState.ContainsKey("Image"))
                    ModelState["Image"].Errors.Clear();
            }
            
            if (ModelState.IsValid && Session["PhotoFileImageData"] != null )
            {
                byte[] imageData = (byte[])Session["PhotoFileImageData"];
                
                var createPhotoDto = new CreatePhotoDto()
                {
                    Image = imageData,
                    ImageMimeType = (string)Session["PhotoFileMimeType"],
                    Title = model.Title,
                    Description = model.Description
                };

                await _photoAlbumService.CreatePhotoAsync(createPhotoDto, token);
                
                Session["PhotoFileImageData"] = null;
                Session["PhotoFileMimeType"] = null;
                Session["PhotoFileName"] = null;

                // Return EmptyResult() for modal window
                return new EmptyResult();
            }
            
            return PartialView(model);
        }
        
        public async Task<ActionResult> GetImageById(int id)
        {
            var requestedETag = Request.Headers["If-None-Match"];

            string requestETagValue = null;
            if (requestedETag != null)
            {
                requestETagValue = requestedETag.Trim('W', '/', '"');
            }

            var image = await _photoAlbumService.GetImageByIdAsync(id, requestETagValue);

            if (image.IsNotModified)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotModified);
            }

            string unifiedData = JsonConvert.SerializeObject(image);
            var responseETagValue = ETagHashCreator.ComputeHash(unifiedData);
            if (requestETagValue == responseETagValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotModified);
            }
            
            var responseETag = new EntityTagHeaderValue("\"" + responseETagValue + "\"", true).ToString();

            Response.Cache.SetCacheability(HttpCacheability.ServerAndPrivate);
            Response.Cache.SetETag(responseETag);

            return File(image.Image, image.ImageMimeType);
        }

        [Authorize]
        public async Task<ActionResult> DeletePhotoById(int id)
        {
            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            await _photoAlbumService.DeletePhotoByIdAsync(id, token);

            return RedirectToAction("UserPageManage", new { username = User.Identity.Name });
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> EditPhoto(int id, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            EditPhotoViewModel editPhotoViewModel = null;
            EditPhotoDto editPhotoDto = await _photoAlbumService.GetEditPhotoByIdAsync(id, token);
            if(editPhotoDto != null)
            {
                editPhotoViewModel = Mapper.Map<EditPhotoViewModel>(editPhotoDto);
            }

            return PartialView(editPhotoViewModel);
        }
        
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPhoto(EditPhotoViewModel editPhotoViewModel, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (!ModelState.IsValid)
            {
                return PartialView(editPhotoViewModel);
            }

            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            EditPhotoDto editPhotoDto = new EditPhotoDto
            {
                Id = editPhotoViewModel.Id,
                Title = editPhotoViewModel.Title,
                Description = editPhotoViewModel.Description
            };

            await _photoAlbumService.EditPhotoAsync(editPhotoDto, token);
            
            // Return EmptyResult() for modal window
            return new EmptyResult();
        }

        public async Task<ActionResult> GetPhotoRating(int id)
        {
            var rating = await _photoAlbumService.GetPhotoRatingAsync(id);

            return Json(rating, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetPhotos(int lastRowId, bool isHistoryBack, SortOrder sorting)
        {
            int pageSize = int.Parse( ConfigurationManager.AppSettings["PageSize"] );

            var photos = await _photoAlbumService.GetPhotosAsync(new PagingParametersDto
            {
                PageNumber = lastRowId,
                PageSize = pageSize,
                Sorting = sorting
            });

            return Json(photos, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetUserPhotos(int lastRowId, bool isHistoryBack, SortOrder sorting, string userName)
        {
            int pageSize = int.Parse( ConfigurationManager.AppSettings["PageSize"] );

            var photos = await _photoAlbumService.GetUserPhotosAsync(new PagingParametersDto
            {
                PageNumber = lastRowId,
                PageSize = pageSize,
                Sorting = sorting
            },
            userName);

            return Json(photos, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetAllUserVotes()
        {
            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            var userVotes = await _photoAlbumService.GetUserVotesAsync(token);

            return Json(userVotes, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetUserVotes(int id)
        {
            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            var userVotes = await _photoAlbumService.GetUserVotesAsync(token, id);

            return Json(userVotes, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> CastPhotoVote(PhotoVoteViewModel model)
        {
            var token = ((ClaimsPrincipal)HttpContext.User).FindFirst("AcessToken").Value;

            var photoVoteDto = Mapper.Map<PhotoVoteDto>(model);

            var result = await _photoAlbumService.CastPhotoVoteAsync(photoVoteDto, token);

            return new HttpStatusCodeResult(result);
        }
    }
}

PhotoAlbum.Client/Views/Photo/CreatePhoto.cshtml
@model PhotoAlbum.Client.Models.CreatePhotoViewModel

@using Resources

@using (Html.BeginForm("CreatePhoto", 
                       "Photo", 
                       new { @returnUrl = ViewBag.ReturnUrl }, 
                       FormMethod.Post, 
                       new { enctype = "multipart/form-data", id = "formForModal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>

        <div class="editor-field">
            @if (Session["PhotoFileName"] != null)
            {
                <label for="photoInput" id="photoInputLabel" class="btn btn-primary">@Session["PhotoFileName"]</label>
            }
            else
            {
                <label for="photoInput" id="photoInputLabel" class="btn btn-primary">@Localization.SelectPhoto</label>
            }
            <input type="file" 
                   name="Image" 
                   id="photoInput" 
                   accept="image/*" 
                   style="display: none" 
                   onchange="document.getElementById('photoInputLabel').innerText = this.value.replace(/^.*[\\\/]/, '');" >
        </div>
        @Html.ValidationMessageFor(m => m.Image, "", new { @class = "text-danger" })
        <br/>

        <div class="editor-label">@Localization.Title</div>
        <div class="editor-field">
            <input type="text" name="Title" value="@Model.Title" class="photoTitleInput" />
        </div>
        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        <br />

        <div class="editor-label">@Localization.Description</div>
        <div class="editor-field">
            <textarea name="Description" class="photoDescriptionTextarea">@Model.Description</textarea>
        </div>
        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        <br />

        <p>
            <input type="submit" name="submit" class="btn btn-primary btn-large" value="@Localization.Save" />
        </p>

    </fieldset>
}

PhotoAlbum.Client/Views/Photo/EditPhoto.cshtml
@model PhotoAlbum.Client.Models.EditPhotoViewModel

@using Resources

@using (Html.BeginForm("EditPhoto", 
                       "Photo", 
                       new { @returnUrl = ViewBag.ReturnUrl }, 
                       FormMethod.Post, 
                       new { enctype = "multipart/form-data", id = "formForModal" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>

        <div class="editor-label">@Localization.Title</div>
        <div class="editor-field">
            <input type="text" name="Title" value="@Model.Title" class="photoTitleInput" />
        </div>
        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
        <br/>

        <div class="editor-label">@Localization.Description</div>
        <div class="editor-field">
            <textarea name="Description" class="photoDescriptionTextarea">@Model.Description</textarea>
        </div>
        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        <br />

        <p>
            <input type="submit" class="dialog-window btn btn-primary btn-large" value="@Localization.Save" formtarget="_parent" />
        </p>

    </fieldset>
}

PhotoAlbum.Client/Views/Photo/UserPageManage.cshtml
@model PhotoAlbum.Client.Models.UserPageViewModel

@*Bundles for rating stars*@
@Scripts.Render("~/bundles/rateyo/myAlias")
@Scripts.Render("~/Scripts/myModal")
@Styles.Render("~/Content/rateyo/myAlias")


@*Sort order*@
<div class="sortOrder">
    <span class="sortNewFirst">
        @Html.RadioButtonFor(m => m.SortPhoto.Sorting, Model.SortPhoto.ByCreationDate, new { Checked = "checked" }) @Resources.Localization.NewFirst
    </span>
    <span class="sortPopularFirst">
        @Html.RadioButtonFor(m => m.SortPhoto.Sorting, Model.SortPhoto.ByRating) @Resources.Localization.PopularFirst
    </span>
</div>

@{
    Model.SortPhoto.Sorting = Model.SortPhoto.ByCreationDate;
}

@*Modal window*@
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body" id="form-container"><div class="te">Please wait...</div></div>
            <div class="modal-footer">
                <button type="button" class="dialog-window btn btn-primary btn-large" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

@*IFrame*@
@*<iframe name="iframe1" width="600" height="400" src="/photo/createphoto" frameborder="1" scrolling="no"></iframe>*@

@*"Add new pohoto" button*@
@Html.ActionLink(Resources.Localization.AddNewPhoto, "CreatePhoto", "Photo", new { @returnUrl = Request.Url.AbsolutePath }, new { @class = "addNewPhotoButton dialog-window btn btn-primary btn-large" })

@*Main photo content section*@
<div id="sectionPhotos"></div>

@*Load indicator*@
<div class="loadingContainer">
    <img id="loading" src="~/Content/img/ajax-loader.gif" alt="" />
</div>

@*Suppotr section*@
<input type="hidden" id="lastRowId" value="1" />

<script>
    $.ajaxSetup({
        beforeSend: function () {
            $("#loading").show();
        },
        complete: function () {
            $("#loading").hide();
        }
    });

    $(document).ready(function () {
        // Add "modal dialog open" button handler (open modal window)
        $("body").on("click", "a.dialog-window", null, function (e) {

            e.preventDefault();

            var $link = $(this);
            var title = $link.text();
            $('#myModal .modal-title').html(title);

            var url = $(this).attr('href');
            if (url.indexOf('#') == 0) {
                $('#myModal').modal('show');
            }
            else {
                $.get(url, function (data) {
                    $('#myModal .te').html(data);
                    $('#myModal').modal({
                        backdrop: 'static',
                        keyboard: false
                    });
                }).then(function () { $('input:text:visible:first').focus(); });
            }

        });

        // Add modal form "submit" button handler
        $("#myModal").on("submit", "#formForModal", function (e) {

            e.preventDefault();

            var form = $(this);

            $.ajax({
                url: form.attr("action"),
                method: form.attr("method"),
                data: new FormData(this),
                success: function (partialResult) {
                    if (!partialResult) {
                        location.reload();
                        return;
                    }
                    $('#myModal .te').html(partialResult);
                },
                cache: false,
                contentType: false,
                processData: false
            });

        });

    });

    // Global variables
    var userVotes = null;
    var sorting = "@Model.SortPhoto.Sorting";

    // On radio button change
    $('input[name="SortPhoto.Sorting"]:radio').change(function () {
        $('#sectionPhotos').empty();
        $("#lastRowId").val(1);
        isPhotoAvaiable = true;
        GetAllCurrentUserVotes();
        sorting = $('input[name="SortPhoto.Sorting"]:checked').val();
        GetPhotosFromNextSection(false, sorting);
    });

    // Get all current user votes
    function GetAllCurrentUserVotes() {
        $.ajax({
        type: 'GET',
        url: '/Photo/GetAllUserVotes',
        dataType: 'json',
        success: function (jsonData) {
            if (jsonData == null) {
                return;
            }
            userVotes = jsonData;
        },
        error: function (jsonData) {
            userVotes = null;
        }
        });
    }

    GetAllCurrentUserVotes();

    // Get default photo data
    $(document).ready(function () {
        GetPhotosFromNextSection(false, sorting);
    });

    // Get next photo data automatic
    $(window).scroll(function () {
        if ($(window).scrollTop() == $(document).height() - $(window).height()) {
            GetPhotosFromNextSection(true, sorting);
        }
    });

    var isRequestPending = false;
    var isPhotoAvaiable = true;

    // Common handler
    function GetPhotosFromNextSection(scrollPage, sort) {
        var lastRowId = ($("#lastRowId").val() * 1);
        var isHistoryBack = (lastRowId > 1 && !scrollPage);

        if (!isRequestPending && isPhotoAvaiable) {
            isRequestPending = true;
            $.ajax({
                type: 'GET',
                url: '/Photo/GetUserPhotos?lastRowId=' + lastRowId + '&isHistoryBack=' + isHistoryBack + '&Sorting=' + sort + '&userName=' + '@Model.UserName',
                dataType: 'json',
                success: function (jsonData) {
                    isRequestPending = false;
                    var rowid = lastRowId + 1;

                    if (jsonData.length === 0) {
                        isPhotoAvaiable = false;

                        if (lastRowId === 1) {
                            var noPhotoYetPlaceholder = '<div class="noPhotoYetPlaceholder">' + '@Resources.Localization.NoPhotosYet' + '</div>';
                            $('#sectionPhotos').append(noPhotoYetPlaceholder);
                        }

                        return;
                    }

                    $.each(jsonData, function (index, item) {
                        var sectionIndex = (isHistoryBack ? index + 1 : rowid);
                        var articleData = "";
                        articleData += '<div class="mainContainer">' +
                                            '<div class="photoContainer"><img src="/Photo/GetImageById/' + item.Id + '" /></div>' +
                                            '<div class="photoHeader">' +
                                                '<span class ="photoTitle">' +
                                                    item.Title +
                                                '</span>' +
                                                '<span class ="photoEditButton">' +
                                                    '<a href="/Photo/EditPhoto/' + item.Id + '?returnUrl=%2F' + '@ViewBag.UserName' + '%2F' + '@ViewBag.Manage' + '" class="dialog-window btn btn-primary btn-large">' + '@Resources.Localization.EditPhoto' + '</a>' +
                                                '</span>' +
                                                '<span class ="photoDeleteButton">' +
                                                    '<a href="/Photo/DeletePhotoById/' + item.Id + '" class="btn btn-primary btn-large" onclick = "return confirm(\'' + '@Resources.Localization.AreYouSureYouWantToDeleteThisPhoto' + '\')">' + '@Resources.Localization.DeletePhoto' + '</a>' +
                                                '</span>' +
                                            '</div>' +
                                            '<div class="photoDescription">' + item.Description + '</div>' +
                                            '<div class="photoOwnerAndDate">' +
                                                '<span class="photoOwner">' + 'Added by ' + '<a href="/' + item.OwnerName + '">' + item.OwnerName + '</a>' + '</span>' +
                                                '<span class="photoDate">' +
                                                    new Date(parseInt(item.CreationDate.replace(/\/Date\((-?\d+)\)\//gi, "$1"))).toString().slice(0, 24) +
                                                '</span>' +
                                            '</div>' +
                                            '<div class="photoRatings">' +
                                                '<div class="photoRating">' +
                                                    '<div class="ratingText">' + '@Resources.Localization.Rating: ' + '</div>' +
                                                    '<div class="starRating">' +
                                                        '<div id="photoRatingId_' + item.Id + '"></div>' +
                                                    '</div>' +
                                                '</div>' +
                                                '<div class="photoUserRating">' +
                                                    '<div class="myRatingText">' + '@Resources.Localization.MyRating: ' + '</div>' +
                                                    '<div class="starRating">' +
                                                        '<div id="photoMyRatingId_' + item.Id + '"></div>' +
                                                    '</div>' +
                                                '</div>' +
                                            '</div>' +
                                       '</div>';
                        $('#sectionPhotos').append(articleData);

                        $(function BuildRatingStar() {
                            $('#photoRatingId_' + item.Id).rateYo({
                                rating: Math.round(item.Rating),
                                fullStar: true,
                                readOnly: true
                            });
                        });

                        $(function BuildUserRatingStar() {
                            let photoRating = 0;
                            if (userVotes != null) {
                                $.each(userVotes, function (index, voteItem) {
                                    if (voteItem.PhotoId === item.Id) {
                                        photoRating = voteItem.Rating;
                                    };
                                });
                            };

                            $('#photoMyRatingId_' + item.Id).rateYo({
                                rating: Math.round(photoRating),
                                fullStar: true,
                            })
                            // On user rating change
                            .on("rateyo.set", function (e, data) {
                                $.post(
                                    "/Photo/CastPhotoVote",
                                    {
                                        PhotoId: item.Id,
                                        Rating: data.rating
                                    },
                                    function onSuccess() {
                                        // Change rating star
                                        $.ajax({
                                            type: 'GET',
                                            url: '/Photo/GetPhotoRating/' + item.Id,
                                            dataType: 'json',
                                            success: function (jsonData) {
                                                if (jsonData == null) {
                                                    return;
                                                }

                                                let photoRating = jsonData.Rating;

                                                $('#photoRatingId_' + item.Id).rateYo("rating", Math.round(photoRating));
                                            },
                                            error: function (jsonData) {
                                                window.location.href = '/Home/Error?message=' + jsonData.responseJSON.ErrorMessage;
                                            }
                                        });
                                    }
                                );
                            });
                        });
                    });

                    if (!isHistoryBack) {
                        $("#lastRowId").val(rowid);
                    }
                },
                error: function (jsonData) {
                    isRequestPending = false;
                    if (jsonData.responseJSON.ErrorMessage) {
                        window.location.href = '/Home/Error?message=' + jsonData.responseJSON.ErrorMessage;
                    }
                    else {
                        window.location.href = '/Home/Error?message=' + '@Resources.Localization.ErrorOops';
                    }
                }
            });
        };

        return false;
    }
</script>